import Head from 'next/head'

export default function Home() {
    return (
        <div className='container'>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className='container'>
                <h1 className='mt-4 font-bold text-2xl'>커피 주문</h1>

                <div className='mt-3'>
                    <input type='text' className='form-control' placeholder='이름을 입력해주세요.'/>
                </div>

                <dl className="row mt-3">
                    <dt className="col-sm-3">
                        <input type='checkbox' className='mr-2'/>에스프레소
                    </dt>
                    <dd className="col-sm-9">2,900원</dd>

                    <dt className="col-sm-3">
                        <input type='checkbox' className='mr-2'/>아메리카노
                    </dt>
                    <dd className="col-sm-9">3,400원</dd>
                </dl>

                <button className='btn btn-primary btn-lg mt-4'>주문</button>
            </div>
        </div>
    )
}
